import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

// Sanity checks for public/robots.txt.
//
// Content-Signal (draft-romm-aipref-contentsignals) is a non-standard
// directive, so the file is hand-authored rather than generated by Next.js's
// `app/robots.ts` (whose serializer drops unknown fields). These tests guard
// against accidental edits — e.g. someone deleting the directive or flipping
// `ai-train=no` to `yes` without intent — and verify the file still exposes
// the basic robots.txt contract (User-agent / Allow / Disallow / Sitemap).

function readRobots(): string {
  return readFileSync(resolve(process.cwd(), "public/robots.txt"), "utf8");
}

describe("public/robots.txt", () => {
  const robots = readRobots();

  it("allows all crawlers by default and blocks /api/", () => {
    expect(robots).toMatch(/User-agent:\s*\*/i);
    expect(robots).toMatch(/Allow:\s*\//i);
    expect(robots).toMatch(/Disallow:\s*\/api\//i);
  });

  it("declares the sitemap URL", () => {
    expect(robots).toMatch(
      /Sitemap:\s*https:\/\/craftcv\.online\/sitemap\.xml/i,
    );
  });

  describe("Content-Signal directive", () => {
    // The directive MUST live inside a User-agent block. Match the directive
    // line itself; the "under User-agent: *" placement is verified separately.
    const contentSignalMatch = robots.match(
      /^Content-Signal:\s*(.+)\s*$/im,
    );

    it("is present", () => {
      expect(contentSignalMatch, "Expected a Content-Signal directive").not.toBe(
        null,
      );
    });

    it("declares exactly the three known categories", () => {
      expect(contentSignalMatch).not.toBe(null);
      const value = contentSignalMatch![1];
      const entries = value
        .split(",")
        .map((s) => s.trim().toLowerCase())
        .sort();
      expect(entries).toEqual(["ai-input=yes", "ai-train=no", "search=yes"]);
    });

    it("ai-train is set to no (site policy: no training)", () => {
      expect(contentSignalMatch).not.toBe(null);
      expect(contentSignalMatch![1].toLowerCase()).toMatch(/ai-train\s*=\s*no/);
    });

    it("search and ai-input are allowed", () => {
      expect(contentSignalMatch).not.toBe(null);
      const value = contentSignalMatch![1].toLowerCase();
      expect(value).toMatch(/search\s*=\s*yes/);
      expect(value).toMatch(/ai-input\s*=\s*yes/);
    });

    it("appears after a User-agent line (i.e. inside a block)", () => {
      // Find the position of the Content-Signal line and check that a
      // User-agent line precedes it (with only directives in between).
      const lines = robots.split(/\r?\n/);
      const csIndex = lines.findIndex((l) =>
        /^Content-Signal:/i.test(l.trim()),
      );
      expect(csIndex, "Content-Signal line not found").toBeGreaterThan(-1);

      const precedingUserAgent = lines
        .slice(0, csIndex)
        .some((l) => /^User-agent:/i.test(l.trim()));
      expect(precedingUserAgent).toBe(true);
    });
  });
});
