import type { Metadata } from "next";

export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://craftcv.online";

export const SITE_NAME = "CraftCV";

// Generated by app/opengraph-image.tsx (prerendered at build time).
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "CraftCV - ATS-Ready CV Generator",
};

/**
 * Open Graph block for a non-root page.
 *
 * Next.js merges `metadata` shallowly: a child segment declaring `openGraph`
 * REPLACES the parent's object wholesale, dropping siteName/type/locale and the
 * opengraph-image the file convention attached at the root. So every page that
 * needs a per-page `og:url` has to restate the shared fields — this keeps that
 * in one place. `title`/`description` are intentionally omitted: Next fills
 * them from the page's own `title`/`description`.
 */
export function pageOpenGraph(path: string): Metadata["openGraph"] {
  return {
    type: "website",
    url: path,
    siteName: SITE_NAME,
    locale: "en_US",
    images: [OG_IMAGE],
  };
}
